
import { v4 as uuid } from "uuid";

export const products = [
 
  {
    _id: uuid(),
    title: "Macrame Wall Hanging",
    description: "Boho-style handmade macrame decor for your walls",
    image: "https://media.istockphoto.com/id/1319548747/photo/close-up-of-womens-hands-weaving-macrame-from-white-cotton-threads-in-a-home-workshop-home.jpg?s=1024x1024&w=is&k=20&c=sm6al6p9nODbX_qEPJWbPUkaQJEupzeVFVZ-5geSuTQ=",
    price: "1200",
    discounted_price: "899",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "6",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Terracotta Lamp",
    description: "Hand-painted terracotta table lamp",
    image: "https://images.unsplash.com/photo-1572242161020-5d60b6335d61?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fFRlcnJhY290dGElMjBMYW1wfGVufDB8fDB8fHww",
    price: "1800",
    discounted_price: "1299",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "5",
    rating: "4.7",
  },
  {
    _id: uuid(),
    title: "Embroidered Cushion Cover",
    description: "Colorful cushion cover with tribal embroidery",
    image: "https://images.unsplash.com/photo-1643883540345-64ebe9258337?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fEVtYnJvaWRlcmVkJTIwQ3VzaGlvbiUyMENvdmVyfGVufDB8fDB8fHww",
    price: "600",
    discounted_price: "450",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "4",
    rating: "4.2",
  },
  {
    _id: uuid(),
    title: "Recycled Wood Shelf",
    description: "Rustic floating shelf made from reclaimed wood",
    image: "https://images.unsplash.com/photo-1573584355722-20b870da775f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8UmVjeWNsZWQlMjBXb29kJTIwU2hlbGZ8ZW58MHx8MHx8fDA%3D",
    price: "2500",
    discounted_price: "1750",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "7",
    rating: "4.8",
  },
  {
    _id: uuid(),
    title: "Block Printed Tapestry",
    description: "Traditional block-printed cotton wall tapestry",
    image: "https://images.unsplash.com/photo-1651993543836-231fe9948ec9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fEJsb2NrJTIwUHJpbnRlZCUyMFRhcGVzdHJ5fGVufDB8fDB8fHww",
    price: "1800",
    discounted_price: "999",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "6",
    rating: "4.6",
  },
  {
    _id: uuid(),
    title: "Jute Rug",
    description: "Hand-woven round jute rug",
    image: "https://images.unsplash.com/photo-1745905308908-25f35bacd146?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SnV0ZSUyMFJ1Z3xlbnwwfHwwfHx8MA%3D%3D",
    price: "3000",
    discounted_price: "2299",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "7",
    rating: "4.9",
  },
  {
    _id: uuid(),
    title: "Hand-painted Coasters",
    description: "Set of 4 wooden coasters with Madhubani painting",
    image: "https://images.unsplash.com/photo-1704652015327-89f3267ae524?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SGFuZCUyMHBhaW50ZWQlMjBDb2FzdGVyc3xlbnwwfHwwfHx8MA%3D%3D",
    price: "800",
    discounted_price: "499",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "3",
    rating: "4.3",
  },
  {
    _id: uuid(),
    title: "Decorative Mirror Frame",
    description: "Hand-carved wooden mirror with ethnic design",
    image: "https://images.unsplash.com/photo-1643376790509-7105bef8e484?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fERlY29yYXRpdmUlMjBNaXJyb3IlMjBGcmFtZXxlbnwwfHwwfHx8MA%3D%3D",
    price: "3200",
    discounted_price: "2499",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "5",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Clay Wall Plate",
    description: "Decorative wall-hanging plate with hand painting",
    image: "https://images.unsplash.com/photo-1694544067536-aed7a92b0354?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2xheSUyMFdhbGwlMjBQbGF0ZXxlbnwwfHwwfHx8MA%3D%3D",
    price: "999",
    discounted_price: "799",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "4",
    rating: "4.4",
  },
  {
    _id: uuid(),
    title: "Bamboo Lantern",
    description: "Eco-friendly hanging bamboo lantern",
    image: "https://plus.unsplash.com/premium_photo-1676030685690-0f1ffeacf2f1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8QmFtYm9vJTIwTGFudGVybnxlbnwwfHwwfHx8MA%3D%3D",
    price: "1500",
    discounted_price: "999",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "5",
    rating: "4.0",
  },
  {
    _id: uuid(),
    title: "Wool Wall Art",
    description: "Handcrafted wool and yarn wall decor",
    image: "https://images.unsplash.com/photo-1626962630357-cad3f9af1bf8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8V29vbCUyMFdhbGwlMjBBcnR8ZW58MHx8MHx8fDA%3D",
    price: "1300",
    discounted_price: "899",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "6",
    rating: "4.2",
  },
  {
    _id: uuid(),
    title: "Ceramic Name Plate",
    description: "Hand-painted custom ceramic name board",
    image: "https://media.istockphoto.com/id/1266078291/photo/plaque.webp?a=1&b=1&s=612x612&w=0&k=20&c=XpX9A0jDF1ghApZMDbQy-jD7_GM7mZRbiy3niEvaTUo=",
    price: "2200",
    discounted_price: "1699",
    category_name: "Handcrafted Home Decor",
    size: "",
    availability: true,
    delivery_time: "7",
    rating: "4.6",
  },
  
    {
      _id: uuid(),
      title: "Terracotta Necklace Set",
      description: "Handcrafted terracotta jewelry set with earthy tones",
      image: "https://images.unsplash.com/photo-1722410180681-9f5a22d7ebb6?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: "1500",
      discounted_price: "1199",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "5",
      rating: "4.7",
    },
    {
      _id: uuid(),
      title: "Beaded Hoop Earrings",
      description: "Colorful hand-beaded hoops perfect for casual wear",
      image: "https://plus.unsplash.com/premium_photo-1732706751101-86004396885d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fEJlYWRlZCUyMEhvb3AlMjBFYXJyaW5nc3xlbnwwfHwwfHx8MA%3D%3D",
      price: "899",
      discounted_price: "699",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "4",
      rating: "4.5",
    },
    {
      _id: uuid(),
      title: "Oxidized Silver Choker",
      description: "Ethnic oxidized silver choker with matching earrings",
      image: "https://media.istockphoto.com/id/2012282669/photo/indian-traditional-jewellery-displayed-in-a-street-shop-for-sale-in-pune-maharashtra-indian.jpg?s=1024x1024&w=is&k=20&c=oI2Y8hkYIweYuORPVH_XHgFshkaMFLgTavcoTJXaAvs=",
      price: "1200",
      discounted_price: "950",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "6",
      rating: "4.6",
    },
    {
      _id: uuid(),
      title: "Meenakari Jhumkas",
      description: "Traditional hand-painted meenakari earrings",
      image: "https://media.istockphoto.com/id/1358783703/photo/indian-traditional-jewellery-displayed-in-a-street-shop-for-sale-in-pune-maharashtra-indian.jpg?s=1024x1024&w=is&k=20&c=JXHXX05wXGvMeGQsyJcYeLQDPn96Dnsp2p3s9xph4qU=",
      price: "1100",
      discounted_price: "849",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "5",
      rating: "4.8",
    },
    {
      _id: uuid(),
      title: "Thread Bangles Set",
      description: "Vibrant bangles wrapped in multicolor silk thread",
      image: "https://media.istockphoto.com/id/1268293077/photo/golden-bangles-in-white-background.jpg?s=1024x1024&w=is&k=20&c=b30TbB-BRmlfjb0PiwF8d8yTaPFeqlTPzyJGd5RRICc=",
      price: "999",
      discounted_price: "749",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "6",
      rating: "4.4",
    },
    {
      _id: uuid(),
      title: "Mirror Work Anklets",
      description: "Rajasthani-style anklets with delicate mirror embellishments",
      image: "https://images.unsplash.com/photo-1729719987303-1d62ffa53129?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWlycm9yJTIwV29yayUyMEFua2xldHMlMjBSYWphc3RoYW5pfGVufDB8fDB8fHww",
      price: "850",
      discounted_price: "599",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "4",
      rating: "4.5",
    },
    {
      _id: uuid(),
      title: "Macramé Pendant Necklace",
      description: "Hand-knotted macramé pendant necklace with wooden beads",
      image: "https://images.unsplash.com/photo-1632212782195-4dad1dc3144c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fE1hY3JhbSVDMyVBOSUyMFBlbmRhbnQlMjBOZWNrbGFjZXxlbnwwfHwwfHx8MA%3D%3D",
      price: "1300",
      discounted_price: "999",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "5",
      rating: "4.7",
    },
    {
      _id: uuid(),
      title: "Clay Charm Bracelets",
      description: "Custom handmade bracelets with clay charms",
      image: "https://images.unsplash.com/photo-1740819920986-8462590eccdb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2xheSUyMENoYXJtJTIwQnJhY2VsZXRzfGVufDB8fDB8fHww",
      price: "700",
      discounted_price: "549",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "4",
      rating: "4.3",
    },
    {
      _id: uuid(),
      title: "Shell Drop Earrings",
      description: "Beach-themed earrings made with real shells",
      image: "https://images.unsplash.com/photo-1682822749969-61a63203c501?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U2hlbGwlMjBEcm9wJTIwRWFycmluZ3N8ZW58MHx8MHx8fDA%3D",
      price: "600",
      discounted_price: "450",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "6",
      rating: "4.4",
    },
    {
      _id: uuid(),
      title: "Pearl Kundan Necklace",
      description: "Elegant kundan necklace with pearl accents",
      image: "https://plus.unsplash.com/premium_photo-1674255466849-b23fc5f5d3eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8UGVhcmwlMjBLdW5kYW4lMjBOZWNrbGFjZXxlbnwwfHwwfHx8MA%3D%3D",
      price: "2800",
      discounted_price: "2199",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "7",
      rating: "4.9",
    },
    {
      _id: uuid(),
      title: "Beaded Tribal Necklace",
      description: "Chunky necklace inspired by tribal patterns and designs",
      image: "https://images.unsplash.com/photo-1719861837593-91dbdd0ed5a0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8QmVhZGVkJTIwVHJpYmFsJTIwTmVja2xhY2V8ZW58MHx8MHx8fDA%3D",
      price: "1600",
      discounted_price: "1250",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "5",
      rating: "4.6",
    },
    {
      _id: uuid(),
      title: "Shell Choker",
      description: "Minimalist choker made with natural seashells",
      image: "https://media.istockphoto.com/id/2184306068/photo/mother-of-pearl-necklaces-in-hand-holding-irregular-stone-chokers-floral-background-nacre.jpg?s=612x612&w=0&k=20&c=9MWMswBz_FMCRironZfS6N3ll0wLL8G0Z_OvaI1jXxY=",
      price: "800",
      discounted_price: "599",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "4",
      rating: "4.5",
    },
    {
      _id: uuid(),
      title: "Wooden Earings Set",
      description: "Rustic pendant and earring set made from carved wood",
      image: "https://media.istockphoto.com/id/2186918445/photo/top-view-of-a-pair-of-antique-earrings-with-luxurious-floral-designs-and-metal-hook-clasps.webp?a=1&b=1&s=612x612&w=0&k=20&c=TC5-St34umTkZ09FBFmDwRicnKusT_S5RjgLaqkpZU4=",
      price: "1000",
      discounted_price: "749",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "5",
      rating: "4.3",
    },
    {
      _id: uuid(),
      title: "Resin Art Earrings",
      description: "Trendy resin earrings with embedded flowers",
      image: "https://media.istockphoto.com/id/1451745186/photo/close-up-earrings-and-pendant-with-floral-elements-photo.webp?a=1&b=1&s=612x612&w=0&k=20&c=bUsCVQQrTpWrFOCxOpsqgyGxsKTEQ5pcBUTT1yn_cco=",
      price: "900",
      discounted_price: "699",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "6",
      rating: "4.6",
    },
    {
      _id: uuid(),
      title: "Fabric Button Rings",
      description: "Adjustable rings made from hand-stitched fabric buttons",
      image: "https://media.istockphoto.com/id/2200577201/photo/portrait-of-happy-bride-looking-through-her-red-veil-in-wedding-ceremony.webp?a=1&b=1&s=612x612&w=0&k=20&c=KkqF2ig19NAqM5D9WjBBySvMs8O4Rz7Y3yZ62yDVXJM=",
      price: "550",
      discounted_price: "399",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "4",
      rating: "4.2",
    },
    {
      _id: uuid(),
      title: "Lac Bangle Set",
      description: "Colorful bangle set made using traditional lac techniques",
      image: "https://media.istockphoto.com/id/1258157670/photo/indian-lac-bangles-indian-traditional-jewelry.webp?a=1&b=1&s=612x612&w=0&k=20&c=qHjSUl8p0Ko4BZZw2VfvLgqWXIM3FUxjPDKefFLmd2Y=",
      price: "1150",
      discounted_price: "899",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "6",
      rating: "4.7",
    },
    {
      _id: uuid(),
      title: "Ethnic Nose Ring",
      description: "Statement nose ring with traditional Indian detailing",
      image: "https://images.unsplash.com/photo-1704281449791-6a8917854b2c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXRobmljJTIwbm9zZSUyMHJpbmdzfGVufDB8fDB8fHww",
      price: "600",
      discounted_price: "449",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "5",
      rating: "4.4",
    },
    {
      _id: uuid(),
      title: "Stone Stud Earrings",
      description: "Simple yet elegant gemstone-studded earrings",
      image: "https://media.istockphoto.com/id/691272130/photo/collection-souvenirs-from-the-orient.webp?a=1&b=1&s=612x612&w=0&k=20&c=9vRenc1vdF-VBgL1ACbuRzop7CQiS8xq7ZaDZfNG3dM=",
      price: "700",
      discounted_price: "549",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "3",
      rating: "4.5",
    },
    {
      _id: uuid(),
      title: "Filigree Work Necklace",
      description: "Delicate necklace featuring traditional filigree craft",
      image: "https://images.unsplash.com/photo-1630250207623-4483fd9077a1?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: "1800",
      discounted_price: "1399",
      category_name: "Jewelry",
      size: "",
      availability: true,
      delivery_time: "7",
      rating: "4.8",
    }
  ,
  // Pottery & Ceramics - 20 items
{
  _id: uuid(),
  title: "Handcrafted Clay Tea Set",
  description: "Eco-friendly terracotta tea set with kettle and cups",
  image: "https://images.unsplash.com/photo-1725280894663-a0e467408f71?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8SGFuZGNyYWZ0ZWQlMjBDbGF5JTIwVGVhJTIwU2V0fGVufDB8fDB8fHww",
  price: "2500",
  discounted_price: "1899",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "5",
  rating: "4.7",
},
{
  _id: uuid(),
  title: "Blue Glazed Ceramic Vase",
  description: "Elegant handmade blue glazed flower vase",
  image: "https://images.unsplash.com/photo-1727337441564-b4d6fa4fa2ec?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Qmx1ZSUyMEdsYXplZCUyMENlcmFtaWMlMjBWYXNlfGVufDB8fDB8fHww",
  price: "1800",
  discounted_price: "1399",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "4",
  rating: "4.6",
},
{
  _id: uuid(),
  title: "Terracotta Planters Set",
  description: "Set of 3 hand-painted terracotta pots",
  image: "https://plus.unsplash.com/premium_photo-1673615349309-e975108613f0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fFRlcnJhY290dGElMjBQbGFudGVycyUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
  price: "1500",
  discounted_price: "1099",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "6",
  rating: "4.5",
},
{
  _id: uuid(),
  title: "Handmade Clay Bowl Set",
  description: "Rustic style set of 4 clay bowls for serving",
  image: "https://images.unsplash.com/photo-1686472950413-9647efea07d5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8SGFuZG1hZGUlMjBDbGF5JTIwQm93bCUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
  price: "1200",
  discounted_price: "899",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "3",
  rating: "4.4",
},
{
  _id: uuid(),
  title: "Decorative Ceramic Plate",
  description: "Wall decor plate with ethnic ceramic painting",
  image: "https://images.unsplash.com/photo-1715690999995-c5ecdc8358e7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8RGVjb3JhdGl2ZSUyMENlcmFtaWMlMjBQbGF0ZXxlbnwwfHwwfHx8MA%3D%3D",
  price: "1000",
  discounted_price: "799",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "5",
  rating: "4.6",
},
{
  _id: uuid(),
  title: "Hand-Thrown Clay Mug",
  description: "Artisan clay coffee mug with earthy tones",
  image: "https://plus.unsplash.com/premium_photo-1717586678487-ae60e31b28f7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8SGFuZCUyMFRocm93biUyMENsYXklMjBNdWd8ZW58MHx8MHx8fDA%3D",
  price: "700",
  discounted_price: "499",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "4",
  rating: "4.3",
},
{
  _id: uuid(),
  title: "Glazed Ceramic Oil Dispenser",
  description: "Artistic oil bottle with blue ceramic glaze",
  image: "https://images.unsplash.com/photo-1652453737873-71050bbc4e17?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8R2xhemVkJTIwQ2VyYW1pYyUyME9pbCUyMERpc3BlbnNlcnxlbnwwfHwwfHx8MA%3D%3D",
  price: "950",
  discounted_price: "699",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "5",
  rating: "4.5",
},
{
  _id: uuid(),
  title: "Miniature Clay Animals",
  description: "Set of handmade tiny clay animal figurines",
  image: "https://plus.unsplash.com/premium_photo-1722100466194-3896a8ad0279?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8TWluaWF0dXJlJTIwQ2xheSUyMEFuaW1hbHN8ZW58MHx8MHx8fDA%3D",
  price: "600",
  discounted_price: "450",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "4",
  rating: "4.2",
},
{
  _id: uuid(),
  title: "Ceramic Wind Chime",
  description: "Soothing wind chime made with ceramic bells",
  image: "https://media.istockphoto.com/id/1255877371/photo/beautiful-handicraft-ceramic-wind-bell-or-wind-jingle-tied-with-a-thread-at-the-window.webp?a=1&b=1&s=612x612&w=0&k=20&c=D4ubU-qFGUjU0qNAUzN3T1wForDUxEYTvnnVjrUfCTs=",
  price: "1300",
  discounted_price: "999",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "5",
  rating: "4.4",
},
{
  _id: uuid(),
  title: "Painted Clay Incense Holder",
  description: "Traditional incense stand with folk motifs",
  image: "https://images.unsplash.com/photo-1552941383-3bd80e299174?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fFBhaW50ZWQlMjBDbGF5JTIwSW5jZW5zZSUyMEhvbGRlcnxlbnwwfHwwfHx8MA%3D%3D",
  price: "500",
  discounted_price: "349",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "3",
  rating: "4.3",
},
{
  _id: uuid(),
  title: "Studio Pottery Soup Bowl",
  description: "High-fired stoneware bowl with brush stroke finish",
  image: "https://images.unsplash.com/photo-1648889094882-69f889a3304f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U3R1ZGlvJTIwUG90dGVyeSUyMFNvdXAlMjBCb3dsfGVufDB8fDB8fHww",
  price: "850",
  discounted_price: "649",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "4",
  rating: "4.6",
},
{
  _id: uuid(),
  title: "Textured Ceramic Storage Jar",
  description: "Air-tight jar with clay lid for storing dry items",
  image: "https://plus.unsplash.com/premium_photo-1681345318617-a398e89c4c71?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8VGV4dHVyZWQlMjBDZXJhbWljJTIwU3RvcmFnZSUyMEphcnxlbnwwfHwwfHx8MA%3D%3D",
  price: "900",
  discounted_price: "699",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "6",
  rating: "4.7",
},
{
  _id: uuid(),
  title: "Handmade Clay Candle Holder",
  description: "Rustic tea light holder crafted from terracotta",
  image: "https://images.unsplash.com/photo-1709214008477-b7c6af2e7c46?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8SGFuZG1hZGUlMjBDbGF5JTIwQ2FuZGxlJTIwSG9sZGVyfGVufDB8fDB8fHww",
  price: "650",
  discounted_price: "499",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "3",
  rating: "4.4",
},
{
  _id: uuid(),
  title: "Clay Diffuser Set",
  description: "Terracotta essential oil diffuser with tray and candle slot",
  image: "https://media.istockphoto.com/id/2174420950/photo/aromatic-candle-in-a-glass-jar-with-an-open-stopper-a-ceramic-mug-on-a-wooden-shelf.webp?a=1&b=1&s=612x612&w=0&k=20&c=GMHUiVmIJk0DLZpU23PJIMWUNiLWscnAMkrbJliAzkk=",
  price: "1150",
  discounted_price: "899",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "5",
  rating: "4.6",
},
// {
//   _id: uuid(),
//   title: "Ceramic Pasta Plate",
//   description: "Flat ceramic plate perfect for pasta and salads",
//   image: "https://images.unsplash.com/photo-1590080876460-5ed0c84a429b?auto=format&fit=crop&w=600&q=60",
//   price: "1000",
//   discounted_price: "749",
//   category_name: "Pottery & Ceramics",
//   size: "",
//   availability: true,
//   delivery_time: "4",
//   rating: "4.5",
// },
{
  _id: uuid(),
  title: "Handcrafted Clay Bell",
  description: "Terracotta hanging bell for home or garden decor",
  image: "https://images.unsplash.com/photo-1596434778220-0d345a953059?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SGFuZGNyYWZ0ZWQlMjBDbGF5JTIwQmVsbHxlbnwwfHwwfHx8MA%3D%3D",
  price: "600",
  discounted_price: "449",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "4",
  rating: "4.3",
},
{
  _id: uuid(),
  title: "Ethnic Clay Wall Tiles",
  description: "Set of 4 hand-painted ceramic tiles for decoration",
  image: "https://images.unsplash.com/photo-1727689484465-c704c115740e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fEV0aG5pYyUyMENsYXklMjBXYWxsJTIwVGlsZXN8ZW58MHx8MHx8fDA%3D",
  price: "1400",
  discounted_price: "1099",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "6",
  rating: "4.6",
},
{
  _id: uuid(),
  title: "Ceramic Pen Holder",
  description: "Colorful clay pen stand for work desks",
  image: "https://plus.unsplash.com/premium_photo-1677517547229-39c1f6c4d8c3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Q2VyYW1pYyUyMFBlbiUyMEhvbGRlcnxlbnwwfHwwfHx8MA%3D%3D",
  price: "400",
  discounted_price: "299",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "3",
  rating: "4.1",
},
{
  _id: uuid(),
  title: "Clay Diyas Set",
  description: "Set of 6 festive hand-painted oil lamps",
  image: "https://media.istockphoto.com/id/2179821874/photo/traditional-clay-diyas-are-arranged-for-diwali-festival-celebration.webp?a=1&b=1&s=612x612&w=0&k=20&c=KkBDSZB1cExectWn536R54m2Z0pJiLh2oMlmv_2iUl4=",
  price: "350",
  discounted_price: "249",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "3",
  rating: "4.4",
},
{
  _id: uuid(),
  title: "Ceramic Ring Dish",
  description: "Delicate ceramic dish for storing jewelry or keys",
  image: "https://plus.unsplash.com/premium_photo-1672976877450-663683d52670?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Q2VyYW1pYyUyMFJpbmclMjBEaXNofGVufDB8fDB8fHww",
  price: "600",
  discounted_price: "449",
  category_name: "Pottery & Ceramics",
  size: "",
  availability: true,
  delivery_time: "4",
  rating: "4.5",
}

  
];
